// Objective-C API for talking to github.com/0xhelloweb3/go-coin-wallet/core/gasnow Go package.
//   gobind -lang=objc github.com/0xhelloweb3/go-coin-wallet/core/gasnow
//
// File is generated by gobind. Do not edit.

#ifndef __Gasnow_H__
#define __Gasnow_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GasnowEstimateGasPrice;
@class GasnowGasNowResult;

@interface GasnowEstimateGasPrice : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field EstimateGasPrice.Fast with unsupported type: *math/big.Int

// skipped field EstimateGasPrice.Rapid with unsupported type: *math/big.Int

// skipped field EstimateGasPrice.Slow with unsupported type: *math/big.Int

// skipped field EstimateGasPrice.Standard with unsupported type: *math/big.Int

@end

@interface GasnowGasNowResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field GasNowResult.Data with unsupported type: map[string]float64

@property (nonatomic) NSString* _Nonnull code;
@end

FOUNDATION_EXPORT GasnowEstimateGasPrice* _Nullable GasnowGetEstimateGasPrice(NSError* _Nullable* _Nullable error);

#endif
