
// Objective-C API for talking to the following Go packages
//
//	github.com/0xhelloweb3/go-coin-wallet/core/gasnow
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gasnow_FRAMEWORK_H__
#define __Gasnow_FRAMEWORK_H__

#include "Gasnow.objc.h"
#include "Universe.objc.h"

#endif
